version: "3.8"
services:
  promociones5b_app:
    container_name: promociones5b_app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    depends_on:
      - promociones5b_db
    networks:
      - promociones5b_network

  promociones5b_nginx:
    container_name: promociones5b_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
    - ./public:/usr/src/app/public
    ports:
      - 80:80
    depends_on:
      - promociones5b_app
    environment:
      NGINX_FPM_HOST: promociones5b_app
      NGINX_ROOT: /usr/src/app/public
    networks:
      - promociones5b_network

  promociones5b_db:
    container_name: promociones5b_db
    image: mysql:8.0.20
    restart: always
    volumes:
      - ./docker/db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: promociones5b
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - promociones5b_network

  phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin
      restart: always
      ports:
      - 8081:80
      links:
      - promociones5b_db
      environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=3000M
      networks:
      - promociones5b_network

  promociones5b_redis:
    container_name: promociones5b_redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - promociones5b_network

networks:
  promociones5b_network:
    driver: bridge